export const ADD_DESIGN_START = 'ADD_DESIGN_START';
export const ADD_DESIGN_SUCCESS = 'ADD_DESIGN_SUCCESS';
export const ADD_DESIGN_FAILURE = 'ADD_DESIGN_FAILURE';
export const ADD_DESIGN_END = 'ADD_DESIGN_END';

export const DELETE_DESIGN_START = 'DELETE_DESIGN_START';
export const DELETE_DESIGN_SUCCESS = 'DELETE_DESIGN_SUCCESS';
export const DELETE_DESIGN_FAILURE = 'DELETE_DESIGN_FAILURE';
export const DELETE_DESIGN_END = 'DELETE_DESIGN_END';

export const UPDATE_DESIGN_START = 'UPDATE_DESIGN_START';
export const UPDATE_DESIGN_SUCCESS = 'UPDATE_DESIGN_SUCCESS';
export const UPDATE_DESIGN_FAILURE = 'UPDATE_DESIGN_FAILURE';
export const UPDATE_DESIGN_END = 'UPDATE_DESIGN_END';

export const DISPLAY_DESIGN_START = 'DISPLAY_DESIGN_START';
export const DISPLAY_DESIGN_SUCCESS = 'DISPLAY_DESIGN_SUCCESS';
export const DISPLAY_DESIGN_FAILURE = 'DISPLAY_DESIGN_FAILURE';
export const DISPLAY_DESIGN_END = 'DISPLAY_DESIGN_END';
