export const ADD_DESIGN_START = 'ADD_DESIGN_START';
export const ADD_DESIGN_SUCCESS = 'ADD_DESIGN_SUCCESS';
export const ADD_DESIGN_FAILURE = 'ADD_DESIGN_FAILURE';
export const ADD_DESIGN_END = 'ADD_DESIGN_END';