export const ADD_STUDY_START = 'ADD_STUDY_START';
export const ADD_STUDY_SUCCESS = 'ADD_STUDY_SUCCESS';
export const ADD_STUDY_FAILURE = 'ADD_STUDY_FAILURE';
export const ADD_STUDY_END = 'ADD_STUDY_END';