export const ADD_STUDY_START = 'ADD_STUDY_START';
export const ADD_STUDY_SUCCESS = 'ADD_STUDY_SUCCESS';
export const ADD_STUDY_FAILURE = 'ADD_STUDY_FAILURE';
export const ADD_STUDY_END = 'ADD_STUDY_END';

export const DELETE_STUDY_START = 'DELETE_STUDY_START';
export const DELETE_STUDY_SUCCESS = 'DELETE_STUDY_SUCCESS';
export const DELETE_STUDY_FAILURE = 'DELETE_STUDY_FAILURE';
export const DELETE_STUDY_END = 'DELETE_STUDY_END';

export const UPDATE_STUDY_START = 'UPDATE_STUDY_START';
export const UPDATE_STUDY_SUCCESS = 'UPDATE_STUDY_SUCCESS';
export const UPDATE_STUDY_FAILURE = 'UPDATE_STUDY_FAILURE';
export const UPDATE_STUDY_END = 'UPDATE_STUDY_END';

export const DISPLAY_STUDY_START = 'DISPLAY_STUDY_START';
export const DISPLAY_STUDY_SUCCESS = 'DISPLAY_STUDY_SUCCESS';
export const DISPLAY_STUDY_FAILURE = 'DISPLAY_STUDY_FAILURE';
export const DISPLAY_STUDY_END = 'DISPLAY_STUDY_END';