export const ADVERTISEMENT_START = 'ADVERTISEMENT_START';
export const ADVERTISEMENT_END = 'ADVERTISEMENT_END';
export const ADVERTISEMENT_SUCCESS = 'ADVERTISEMENT_SUCCESS';
export const ADVERTISEMENT_FAILURE = 'ADVERTISEMENT_FAILURE';

export const CREATE_ADVERT_REQUEST = 'CREATE_ADVERT_REQUEST';
export const CREATE_ADVERT_SUCCESS = 'CREATE_ADVERT_SUCCESS';
export const CREATE_ADVERT_FAILURE = 'CREATE_ADVERT_FAILURE';
export const CREATE_ADVERT_END = 'CREATE_ADVERT_END';

export const DISPLAY_ADVERT_START = 'DISPLAY_ADVERT_REQUEST';
export const DISPLAY_ADVERT_SUCCESS = 'DISPLAY_ADVERT_SUCCESS';
export const DISPLAY_ADVERT_FAILURE = 'DISPLAY_ADVERT_FAILURE';
export const DISPLAY_ADVERT_END = 'DISPLAY_ADVERT_END';

export const DELETE_ADVERTISEMENT_START = 'DELETE_ADVERTISEMENT_START';
export const DELETE_ADVERTISEMENT_SUCCESS = 'DELETE_ADVERTISEMENT_SUCCESS';
export const DELETE_ADVERTISEMENT_FAILURE = 'DELETE_ADVERTISEMENT_FAILURE';
export const DELETE_ADVERTISEMENT_END = 'DELETE_ADVERTISEMENT_END';

export const UPDATE_ADVERTISEMENT_START = 'UPDATE_ADVERTISEMENT_START';
export const UPDATE_ADVERTISEMENT_SUCCESS = 'UPDATE_ADVERTISEMENT_SUCCESS';
export const UPDATE_ADVERTISEMENT_FAILURE = 'UPDATE_ADVERTISEMENT_FAILURE';
export const UPDATE_ADVERTISEMENT_END = 'UPDATE_ADVERTISEMENT_END';