export const ADVERTISEMENT_START = 'ADVERTISEMENT_START';
export const ADVERTISEMENT_END = 'ADVERTISEMENT_END';
export const ADVERTISEMENT_SUCCESS = 'ADVERTISEMENT_SUCCESS';
export const ADVERTISEMENT_FAILURE = 'ADVERTISEMENT_FAILURE';
