export const ADVERTISEMENT_START = 'ADVERTISEMENT_START';
export const ADVERTISEMENT_END = 'ADVERTISEMENT_END';
export const ADVERTISEMENT_SUCCESS = 'ADVERTISEMENT_SUCCESS';
export const ADVERTISEMENT_FAILURE = 'ADVERTISEMENT_FAILURE';

export const CREATE_ADVERT_REQUEST = 'CREATE_ADVERT_REQUEST';
export const CREATE_ADVERT_SUCCESS = 'CREATE_ADVERT_SUCCESS';
export const CREATE_ADVERT_FAILURE = 'CREATE_ADVERT_FAILURE';
export const CREATE_ADVERT_END = 'CREATE_ADVERT_END';
