export const ANNOUNCEMENT_START = 'ANNOUNCEMENT_START';
export const ANNOUNCEMENT_END = 'ANNOUNCEMENT_END';
export const ANNOUNCEMENT_SUCCESS = 'ANNOUNCEMENT_SUCCESS';
export const ANNOUNCEMENT_FAILURE = 'ANNOUNCEMENT_FAILURE';

export const CREATE_ANNOUNCEMENT_REQUEST = 'CREATE_ANNOUNCEMENT_REQUEST';
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';
export const CREATE_ANNOUNCEMENT_FAILURE = 'CREATE_ANNOUNCEMENT_FAILURE';
export const CREATE_ANNOUNCEMENT_END = 'CREATE_ANNOUNCEMENT_END';
