export const ANNOUNCEMENT_START = 'ANNOUNCEMENT_START';
export const ANNOUNCEMENT_END = 'ANNOUNCEMENT_END';
export const ANNOUNCEMENT_SUCCESS = 'ANNOUNCEMENT_SUCCESS';
export const ANNOUNCEMENT_FAILURE = 'ANNOUNCEMENT_FAILURE';

export const CREATE_ANNOUNCEMENT_REQUEST = 'CREATE_ANNOUNCEMENT_REQUEST';
export const CREATE_ANNOUNCEMENT_SUCCESS = 'CREATE_ANNOUNCEMENT_SUCCESS';
export const CREATE_ANNOUNCEMENT_FAILURE = 'CREATE_ANNOUNCEMENT_FAILURE';
export const CREATE_ANNOUNCEMENT_END = 'CREATE_ANNOUNCEMENT_END';

export const DELETE_ANNOUNCEMENT_START = 'DELETE_ANNOUNCEMENT_START';
export const DELETE_ANNOUNCEMENT_SUCCESS = 'DELETE_ANNOUNCEMENT_SUCCESS';
export const DELETE_ANNOUNCEMENT_FAILURE = 'DELETE_ANNOUNCEMENT_FAILURE';
export const DELETE_ANNOUNCEMENT_END = 'DELETE_ANNOUNCEMENT_END';

export const UPDATE_ANNOUNCEMENT_START = 'UPDATE_ANNOUNCEMENT_START';
export const UPDATE_ANNOUNCEMENT_SUCCESS = 'UPDATE_ANNOUNCEMENT_SUCCESS';
export const UPDATE_ANNOUNCEMENT_FAILURE = 'UPDATE_ANNOUNCEMENT_FAILURE';
export const UPDATE_ANNOUNCEMENT_END = 'UPDATE_ANNOUNCEMENT_END';