export const ANNOUNCEMENT_START = 'ANNOUNCEMENT_START';
export const ANNOUNCEMENT_END = 'ANNOUNCEMENT_END';
export const ANNOUNCEMENT_SUCCESS = 'ANNOUNCEMENT_SUCCESS';
export const ANNOUNCEMENT_FAILURE = 'ANNOUNCEMENT_FAILURE';
