export const BEST_PRODUCTS_START = 'BEST_PRODUCTS_START';
export const BEST_PRODUCTS_END = 'BEST_PRODUCTS_END';
export const BEST_PRODUCTS_SUCCESS = 'BEST_PRODUCTS_SUCCESS';
export const BEST_PRODUCTS_FAILURE = 'BEST_PRODUCTS_FAILURE';
