export const CREATE_BONUS_START = 'CREATE_BONUS_START';
export const CREATE_BONUS_SUCCESS = 'CREATE_BONUS_SUCCESS';
export const CREATE_BONUS_FAILURE = 'CREATE_BONUS_FAILURE';
export const CREATE_BONUS_END = 'CREATE_BONUS_END';

export const DISPLAY_BONUS_START = 'DISPLAY_BONUS_START';
export const DISPLAY_BONUS_SUCCESS = 'DISPLAY_BONUS_SUCCESS';
export const DISPLAY_BONUS_FAILURE = 'DISPLAY_BONUS_FAILURE';
export const DISPLAY_BONUS_END = 'DISPLAY_BONUS_END';

export const DELETE_BONUS_START = 'DELETE_BONUS_START';
export const DELETE_BONUS_END = 'DELETE_BONUS_END';
export const DELETE_BONUS_SUCCESS = 'DELETE_BONUS_SUCCESS';
export const DELETE_BONUS_FAILURE = 'DELETE_BONUS_FAILURE';

export const ALLOW_BONUS_START = 'ALLOW_BONUS_START';
export const ALLOW_BONUS_END = 'ALLOW_BONUS_END';
export const ALLOW_BONUS_SUCCESS = 'ALLOW_BONUS_SUCCESS';
export const ALLOW_BONUS_FAILURE = 'ALLOW_BONUS_FAILURE';