export const FETCH_DESIGN_START = 'FETCH_DESIGN_START';
export const FETCH_DESIGN_END = 'FETCH_DESIGN_END';
export const FETCH_DESIGN_SUCCESS = 'FETCH_DESIGN_SUCCESS';
export const FETCH_DESIGN_FAILURE = 'FETCH_DESIGN_FAILURE';

export const FETCH_SPECIFIC_DESIGN_START = 'FETCH_SPECIFIC_DESIGN_START';
export const FETCH_SPECIFIC_DESIGN_END = 'FETCH_SPECIFIC_DESIGN_END';
export const FETCH_SPECIFIC_DESIGN_SUCCESS = 'FETCH_SPECIFIC_DESIGN_SUCCESS';
export const FETCH_SPECIFIC_DESIGN_FAILURE = 'FETCH_SPECIFIC_DESIGN_FAILURE';
