export const EXTERNAL_ADVERTISEMENT_START = 'EXTERNAL_ADVERTISEMENT_START';
export const EXTERNAL_ADVERTISEMENT_END = 'EXTERNAL_ADVERTISEMENT_END';
export const EXTERNAL_ADVERTISEMENT_SUCCESS = 'EXTERNAL_ADVERTISEMENT_SUCCESS';
export const EXTERNAL_ADVERTISEMENT_FAILURE = 'EXTERNAL_ADVERTISEMENT_FAILURE';
