export const CREATE_FEEDBACK_REQUEST = 'CREATE_FEEDBACK_REQUEST';
export const CREATE_FEEDBACK_SUCCESS = 'CREATE_FEEDBACK_SUCCESS';
export const CREATE_FEEDBACK_FAILURE = 'CREATE_FEEDBACK_FAILURE';
export const CREATE_FEEDBACK_END = 'CREATE_FEEDBACK_END';

export const DISPLAY_FEEDBACK_START = 'DISPLAY_FEEDBACK_START';
export const DISPLAY_FEEDBACK_SUCCESS = 'DISPLAY_FEEDBACK_SUCCESS';
export const DISPLAY_FEEDBACK_FAILURE = 'DISPLAY_FEEDBACK_FAILURE';
export const DISPLAY_FEEDBACK_END = 'DISPLAY_FEEDBACK_END';

export const DELETE_FEEDBACK_START = 'DELETE_FEEDBACK_START';
export const DELETE_FEEDBACK_SUCCESS = 'DELETE_FEEDBACK_SUCCESS';
export const DELETE_FEEDBACK_FAILURE = 'DELETE_FEEDBACK_FAILURE';
export const DELETE_FEEDBACK_END = 'DELETE_FEEDBACK_END';