export const CREATE_NEWS_REQUEST = 'CREATE_NEWS_REQUEST';
export const CREATE_NEWS_SUCCESS = 'CREATE_NEWS_SUCCESS';
export const CREATE_NEWS_FAILURE = 'CREATE_NEWS_FAILURE';
export const CREATE_NEWS_END = 'CREATE_NEWS_END';

export const DISPLAY_NEWS_REQUEST = 'DISPLAY_NEWS_REQUEST';
export const DISPLAY_NEWS_SUCCESS = 'DISPLAY_NEWS_SUCCESS';
export const DISPLAY_NEWS_FAILURE = 'DISPLAY_NEWS_FAILURE';
export const DISPLAY_NEWS_END = 'DISPLAY_NEWS_END';

export const DELETE_NEWS_START = 'DELETE_NEWS_START';
export const DELETE_NEWS_SUCCESS = 'DELETE_NEWS_SUCCESS';
export const DELETE_NEWS_FAILURE = 'DELETE_NEWS_FAILURE';
export const DELETE_NEWS_END = 'DELETE_NEWS_END';

export const UPDATE_NEWS_START = 'UPDATE_NEWS_START';
export const UPDATE_NEWS_SUCCESS = 'UPDATE_NEWS_SUCCESS';
export const UPDATE_NEWS_FAILURE = 'UPDATE_NEWS_FAILURE';
export const UPDATE_NEWS_END = 'UPDATE_NEWS_END';