export const ORDER_PRODUCT_START = 'ORDER_PRODUCT_START';
export const ORDER_PRODUCT_END = 'ORDER_PRODUCT_END';
export const ORDER_PRODUCT_SUCCESS = 'ORDER_PRODUCT_SUCCESS';
export const ORDER_PRODUCT_FAILURE = 'ORDER_PRODUCT_FAILURE';

export const CLIENT_ORDERS_START = 'CLIENT_ORDERS_START';
export const CLIENT_ORDERS_END = 'CLIENT_ORDERS_END';
export const CLIENT_ORDERS_SUCCESS = 'CLIENT_ORDERS_SUCCESS';
export const CLIENT_ORDERS_FAILURE = 'CLIENT_ORDERS_FAILURE';
