export const CREATE_PRODUCT_REQUEST = 'CREATE_PRODUCT_REQUEST';
export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAILURE = 'CREATE_PRODUCT_FAILURE';
export const CREATE_PRODUCT_END = 'CREATE_PRODUCT_END';

export const DELETE_PRODUCT_START = 'DELETE_PRODUCT_START';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILURE = 'DELETE_PRODUCT_FAILURE';
export const DELETE_PRODUCT_END = 'DELETE_PRODUCT_END';

export const UPDATE_PRODUCT_START = 'UPDATE_PRODUCT_START';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILURE = 'UPDATE_PRODUCT_FAILURE';
export const UPDATE_PRODUCT_END = 'UPDATE_PRODUCT_END';

export const BEST_PRODUCT_START = 'BEST_PRODUCT_START';
export const BEST_PRODUCT_SUCCESS = 'BEST_PRODUCT_SUCCESS';
export const BEST_PRODUCT_FAILURE = 'BEST_PRODUCT_FAILURE';
export const BEST_PRODUCT_END = 'BEST_PRODUCT_END';

export const ADD_QTY_START = 'ADD_QTY_START';
export const ADD_QTY_SUCCESS = 'ADD_QTY_SUCCESS';
export const ADD_QTY_FAILURE = 'ADD_QTY_FAILURE';
export const ADD_QTY_END = 'ADD_QTY_END';