export const CREATE_REFUND_REQUEST = 'CREATE_REFUND_REQUEST';
export const CREATE_REFUND_SUCCESS = 'CREATE_REFUND_SUCCESS';
export const CREATE_REFUND_FAILURE = 'CREATE_REFUND_FAILURE';
export const CREATE_REFUND_END = 'CREATE_REFUND_END';
