export const CREATE_REFUND_REQUEST = 'CREATE_REFUND_REQUEST';
export const CREATE_REFUND_SUCCESS = 'CREATE_REFUND_SUCCESS';
export const CREATE_REFUND_FAILURE = 'CREATE_REFUND_FAILURE';
export const CREATE_REFUND_END = 'CREATE_REFUND_END';

export const DISPLAY_REFUND_START = 'DISPLAY_REFUND_START';
export const DISPLAY_REFUND_SUCCESS = 'DISPLAY_REFUND_SUCCESS';
export const DISPLAY_REFUND_FAILURE = 'DISPLAY_REFUND_FAILURE';
export const DISPLAY_REFUND_END = 'DISPLAY_REFUND_END';

export const CLIENT_REFUND_START = 'CLIENT_REFUND_START';
export const CLIENT_REFUND_SUCCESS = 'CLIENT_REFUND_SUCCESS';
export const CLIENT_REFUND_FAILURE = 'CLIENT_REFUND_FAILURE';
export const CLIENT_REFUND_END = 'CLIENT_REFUND_END';

export const STATUS_REFUND_START = 'STATUS_REFUND_START';
export const STATUS_REFUND_SUCCESS = 'STATUS_REFUND_SUCCESS';
export const STATUS_REFUND_FAILURE = 'STATUS_REFUND_FAILURE';
export const STATUS_REFUND_END = 'STATUS_REFUND_END';
