export const SIDEBAR_DISPLAY_START = 'SIDEBAR_DISPLAY_START';
export const SIDEBAR_DISPLAY_END = 'SIDEBAR_DISPLAY_END';
export const SIDEBAR_DISPLAY_SUCCESS = 'SIDEBAR_DISPLAY_SUCCESS';
export const SIDEBAR_DISPLAY_FAILURE = 'SIDEBAR_DISPLAY_FAILURE';
