export const UPDATE_TRANSPORT_START = 'UPDATE_TRANSPORT_START';
export const UPDATE_TRANSPORT_SUCCESS = 'UPDATE_TRANSPORT_SUCCESS';
export const UPDATE_TRANSPORT_FAILURE = 'UPDATE_TRANSPORT_FAILURE';
export const UPDATE_TRANSPORT_END = 'UPDATE_TRANSPORT_END';

export const DISPLAY_TRANSPORT_START = 'DISPLAY_TRANSPORT_START';
export const DISPLAY_TRANSPORT_SUCCESS = 'DISPLAY_TRANSPORT_SUCCESS';
export const DISPLAY_TRANSPORT_FAILURE = 'DISPLAY_TRANSPORT_FAILURE';
export const DISPLAY_TRANSPORT_END = 'DISPLAY_TRANSPORT_END';

export const SECTOR_DISPLAY_START = 'SECTOR_DISPLAY_START';
export const SECTOR_DISPLAY_END = 'SECTOR_DISPLAY_END';
export const SECTOR_DISPLAY_SUCCESS = 'SECTOR_DISPLAY_SUCCESS';
export const SECTOR_DISPLAY_FAILURE = 'SECTOR_DISPLAY_FAILURE';