export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_END = 'USER_SIGNUP_END';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';

export const USER_LOGIN_START = 'USER_LOGIN_START';
export const USER_LOGIN_END = 'USER_LOGIN_END';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE';

export const DISPLAY_USERS_START = 'DISPLAY_USERS_START';
export const DISPLAY_USERS_END = 'DISPLAY_USERS_END';
export const DISPLAY_USERS_SUCCESS = 'DISPLAY_USERS_SUCCESS';
export const DISPLAY_USERS_FAILURE = 'DISPLAY_USERS_FAILURE';

export const USER_LOGOUT_START = 'USER_LOGOUT_START';
export const USER_LOGOUT_END = 'USER_LOGOUT_END';
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';
export const USER_LOGOUT_FAILURE = 'USER_LOGOUT_FAILURE';

export const DELETE_USER_START = 'DELETE_USER_START';
export const DELETE_USER_END = 'DELETE_USER_END';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const UPDATE_USER_START = 'UPDATE_USER_START';
export const UPDATE_USER_END = 'UPDATE_USER_END';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';
