export const USER_SIGNUP_START = 'USER_SIGNUP_START';
export const USER_SIGNUP_END = 'USER_SIGNUP_END';
export const USER_SIGNUP_SUCCESS = 'USER_SIGNUP_SUCCESS';
export const USER_SIGNUP_FAILURE = 'USER_SIGNUP_FAILURE';
